volumes:
  db_data:
    name: ecos_db_data
services:
  server:
    image: registry.git.ledes.net/felipe_soupinski/ecos-metrics:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - db_data:/app/server/db
    ports:
      - "5000:5000"
