export const scenariosData = [
  {
    title: "Cenário 1 (Declínio da Comunidade de Desenvolvedores)",
    text: "A Company 1 é uma plataforma de desenvolvimento low-code que existe há 5 anos. Nos últimos 6 meses, a equipe de Developer Relations notou:",
    list: [
      "Diminuição na participação em eventos online",
      "Menos contribuições na documentação",
      "Queda no número de extensões/plugins novos",
      "Aumento em reclamações sobre problemas não resolvidos",
      "Competidores ganhando mais atenção nas redes sociais",
    ],
  },
  {
    title: "Cenário 2 (Fragmentação do Ecossistema)",
    text: "A Company 2 desenvolve um framework open-source para microsserviços que ganhou popularidade rapidamente. Em 2 anos, o ecossistema cresceu para incluir:",
    list: [
      "Mais de 200 plugins de terceiros",
      "Múltiplas versões sendo mantidas simultaneamente",
      "Diferentes implementações para várias linguagens de programação",
      "Forks significativos com funcionalidades divergentes",
      "Confusão dos usuários sobre qual versão/implementação usar",
      "Incompatibilidades entre plugins",
      "Sobrecarga da equipe para manter compatibilidade",
      "Divergência nas práticas de desenvolvimento entre comunidades",
    ],
  },
  {
    title: "Cenário 3 (Transição de Modelo de Negócio)",
    text: "A Company 3 está planejando migrar seu popular IDE de um modelo de licença perpétua para um modelo baseado em assinatura com recursos na nuvem. O ecossistema atual inclui:",
    list: [
      "Grande base de plugins gratuitos e pagos",
      "Comunidade ativa de desenvolvedores de extensões",
      "Forte presença em ambiente corporativo",
      "Integração com várias ferramentas terceiras",
      "Possível resistência da comunidade à mudança",
      "Risco de perda de desenvolvedores de plugins",
      "Necessidade de manter compatibilidade com integrações existentes",
      "Competidores podem aproveitar a transição para atrair usuários",
    ],
  },
  {
    title: "Cenário 4 (Escalabilidade do Suporte)",
    text: "A Company 4 é uma plataforma de APIs que cresceu de 1.000 para 50.000 desenvolvedores em 18 meses. Seu ecossistema inclui:",
    list: [
      "SDKs para 12 linguagens diferentes",
      "Marketplace de integrações",
      "Documentação em 4 idiomas",
      "Programa de embaixadores técnicos",
      "Tempo de resposta crescente no suporte",
      "Documentação desatualizada em alguns idiomas",
      "Inconsistências entre diferentes SDKs",
      "Dificuldade em manter qualidade das integrações no marketplace",
      "Sobrecarga dos embaixadores técnicos",
    ],
  },
  {
    title: "Cenário 5 (Obsolescência Tecnológica)",
    text: "A Company 5 mantém um framework front-end popular há 8 anos. Recentemente:",
    list: [
      "Novas tecnologias web emergiram com força",
      "Desenvolvedores mais jovens preferem alternativas mais modernas",
      "Empresas começaram a migrar para novos frameworks",
      "Contribuidores principais começaram a sair",
      "Ainda existe uma grande base instalada",
      "Muitas empresas dependem do framework",
      "Há um ecossistema robusto de componentes e ferramentas",
      "A comunidade de longa data ainda é ativa",
    ],
  },
  {
    title: "Cenário 6 (Internacionalização do Ecossistema)",
    text: "A Company 6, uma empresa de banco de dados NoSQL, viu crescimento explosivo em mercados emergentes, especialmente Ásia e América Latina. O ecossistema atual é:",
    list: [
      "Predominantemente em inglês",
      "Centralizado em comunidades norte-americanas e europeias",
      "Mantido por uma equipe principalmente ocidental",
      "Barreiras linguísticas na documentação e suporte",
      "Diferentes expectativas culturais de comunidade",
      "Fuso horário complicando eventos e suporte",
      "Padrões de uso diferentes por região",
      "Necessidade de adaptar materiais educacionais",
    ],
  },
  {
    title: "Cenário 7 (Perda de Contribuidores Centrais)",
    text: "A Company 7 é um framework de microsserviços com alta dependência em alguns desenvolvedores-chave para manutenção de componentes críticos. A situação atual é:",
    list: [
      "Dois dos principais mantenedores deixaram o projeto",
      "O conhecimento sobre partes críticas da arquitetura estava centralizado",
      "A documentação técnica está desatualizada",
      "Novos contribuidores têm dificuldade em assumir as responsabilidades",
      "Issues começam a se acumular sem resolução",
      "A comunidade expressa preocupação sobre o futuro do framework",
    ],
  },
  {
    title: "Cenário 8 (Sinais de Obsolescência Tecnológica)",
    text: "A Company 8 é um sistema de banco de dados NoSQL que existe há 10 anos. O ecossistema apresenta:",
    list: [
      "Performance degradando gradualmente",
      "Dificuldade em acompanhar requisitos modernos de segurança",
      "Incompatibilidade crescente com novas tecnologias",
      "Arquitetura difícil de modificar para atender novos casos de uso",
      "Competidores oferecendo soluções mais modernas e eficientes",
      "Base de usuários começando a migrar para outras soluções",
    ],
  },
  {
    title: "Cenário 9 (Falta de Engajamento Comunitário)",
    text: "A Company 9 é um framework de desenvolvimento front-end que mostra os seguintes sinais:",
    list: [
      "Diminuição na taxa de resposta no Stack Overflow",
      "Redução no número de novos contribuidores",
      "Queda na frequência de commits e pull requests",
      "Aumento no tempo médio de resolução de issues",
      "Baixa participação em eventos da comunidade",
      "Diminuição na criação de conteúdo educacional pela comunidade",
    ],
  },
  {
    title: "Cenário 10 (Vulnerabilidades de Segurança)",
    text: "A Company 10 é uma plataforma de computação em nuvem que enfrenta a seguinte situação:",
    list: [
      "Descoberta de múltiplas vulnerabilidades críticas",
      "Atrasos significativos nas atualizações de segurança",
      "Perda de certificações de segurança importantes",
      "Migração de clientes corporativos para concorrentes",
      "Diminuição da confiança da comunidade após incidentes",
      "Dificuldade em manter conformidade com novas regulamentações",
    ],
  },
  {
    title: "Cenário 11 (Gestão e Comunidade)",
    text: "A Company 11 é uma plataforma de desenvolvimento de aplicativos móveis que apresenta o seguinte cenário:",
    list: [
      "Decisões unilaterais da organização central gerando insatisfação na comunidade",
      "Falta de transparência nas mudanças de roadmap",
      "Conflitos entre objetivos comerciais e necessidades da comunidade",
      "Inconsistência nas políticas de governança",
      "Demora na aprovação de contribuições da comunidade",
      "Comunicação deficiente sobre descontinuação de recursos",
      "Aumento nas reclamações públicas dos desenvolvedores",
    ],
  },
  {
    title: "Cenário 12 (Aspectos Financeiros)",
    text: "A Company 12 é uma plataforma de desenvolvimento de IA que enfrenta:",
    list: [
      "Custos crescentes de infraestrutura e manutenção",
      "Dificuldade em monetizar serviços premium",
      "Competidores oferecendo alternativas gratuitas",
      "Diminuição no suporte financeiro de patrocinadores",
      "Aumento nos custos de conformidade regulatória",
      "Recursos limitados para desenvolvimento",
      "Queda no número de clientes empresariais",
    ],
  },
  {
    title: "Cenário 13 (Evolução Técnica e Qualidade de Código)",
    text: "Uma plataforma de desenvolvimento de software open-source busca melhorar a qualidade e manutenibilidade de seu código-base. Os desafios encontrados são:",
    list: [
      "Crescimento exponencial de linhas de código",
      "Aumento na complexidade do projeto",
      "Necessidade de reduzir dívida técnica",
      "Manutenção da qualidade do código",
      "Gestão eficiente de bugs e commits",
    ],
  },
  {
    title: "Cenário 14 (Colaboração e Recursos de Rede)",
    text: "Uma startup de tecnologia busca otimizar a colaboração entre equipes distribuídas globalmente. Os desafios são:",
    list: [
      "Coordenação entre times em diferentes fusos horários",
      "Maximizar produtividade colaborativa",
      "Criação de valor através de colaboração",
      "Gestão eficiente de releases",
      "Otimização dos recursos de rede",
    ],
  },
  {
    title: "Cenário 15 (Sustentabilidade e Independência Tecnológica)",
    text: "Um ecossistema de software de código aberto busca garantir sua relevância e adaptabilidade a longo prazo. Os desafios incluem:",
    list: [
      "Manter independência tecnológica",
      "Garantir compatibilidade entre componentes",
      "Assegurar sustentabilidade a longo prazo",
      "Gerenciar métricas de nós e interconexões",
      "Adaptação a mudanças tecnológicas sem perder identidade",
    ],
  },
];
